// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBK1wiwRVRRCvYfvgmrB3X_Fe8jVftT564',
    appId: '1:724668509525:web:5f7347e8e47f43d4f3d3dc',
    messagingSenderId: '724668509525',
    projectId: 'airecipe-e2185',
    authDomain: 'airecipe-e2185.firebaseapp.com',
    storageBucket: 'airecipe-e2185.firebasestorage.app',
    measurementId: 'G-1D12E69377',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ZihEI9TLS8CRqQh27ExywhZnvHQegGs',
    appId: '1:724668509525:android:2e53d778336095e9f3d3dc',
    messagingSenderId: '724668509525',
    projectId: 'airecipe-e2185',
    storageBucket: 'airecipe-e2185.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaw5MjG6gB7c_XZ-0W-jEER3ZcCLlnjIA',
    appId: '1:724668509525:ios:51fdc437790f6b91f3d3dc',
    messagingSenderId: '724668509525',
    projectId: 'airecipe-e2185',
    storageBucket: 'airecipe-e2185.firebasestorage.app',
    iosBundleId: 'com.example.airecipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBK1wiwRVRRCvYfvgmrB3X_Fe8jVftT564',
    appId: '1:724668509525:web:778a3aaa071e720df3d3dc',
    messagingSenderId: '724668509525',
    projectId: 'airecipe-e2185',
    authDomain: 'airecipe-e2185.firebaseapp.com',
    storageBucket: 'airecipe-e2185.firebasestorage.app',
    measurementId: 'G-52H859SHE1',
  );
}
